version: 0.0
os: linux
files:
  - source: /
    destination: "%WP_DIRECTORY%" 
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh "%WP_DIRECTORY%"
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
